Fix unexpected state change
amolabs/amoabci pull request #159
Opened 2019-11-05 05:42 UTC by h0n9

- ignore setting 0 value to store(update test codes)
- fix app_config to get applied properly
- add "config/lockup_period" property to test_script/genesis.json

resolves https://github.com/amolabs/amoabci/issues/158

2019-11-05 06:00 UTC, h0n9 commented
It seems necessary to update integration test of `test_script/all.sh` to test `lockup_period`, `locked` and `unlocked` stakes. But, it is recommended to consider the test can take lots of time to wait for `locked` stakes to get `unlocked`.

2019-11-06 00:22 UTC, Lbird requested changes

2019-11-06 00:22 UTC, Lbird commented on amo/tx/transfer.go
> +	tags := []tm.KVPair{
Remove this. This should be handled in other PR.

2019-11-06 00:47 UTC, Lbird approved these changes

2019-11-06 00:48 UTC, merged