Add 'staking amount unit check' with test codes
amolabs/amoabci pull request #184
Opened 2019-12-13 10:11 UTC by h0n9

resolves https://github.com/amolabs/amoabci/issues/164

2019-12-16 01:50 UTC, Lbird requested changes

2019-12-16 01:50 UTC, Lbird commented on test_script/genesis.json
> +		"min_staking_unit": "10000",
check indentation

2019-12-16 07:26 UTC, Lbird approved these changes

2019-12-16 07:26 UTC, merged

2019-12-17 05:59 UTC, h0n9 commented
update for docs in https://github.com/amolabs/docs/commit/ba3666339bedfa18d53edc4bc9da08cc15ae73bc