Prevent double stake
amolabs/amoabci pull request #188
Opened 2019-12-16 08:32 UTC by h0n9

- set conditions for checking 0 amount while executing txs
- handle stake tx only as a newly generated locked stake
- add test codes for stake and overall txs

resolves https://github.com/amolabs/amoabci/issues/185

2019-12-17 04:44 UTC, h0n9 commented
update for docs in https://github.com/amolabs/docs/commit/d9b0e640bc0654f01ecc47273a431db32999612b

2019-12-17 06:36 UTC, Lbird requested changes

2019-12-17 06:36 UTC, Lbird commented on amo/code/code.go
> +	TxCodeUnavailableAmount
InvalidAmount, and change rest of the codes.

2019-12-17 06:36 UTC, Lbird commented on amo/tx/delegate.go
> +		return code.TxCodeUnavailableAmount, "unavailable amount", nil
invalid amount

2019-12-17 06:36 UTC, Lbird commented on amo/tx/stake.go
> -	} else if bytes.Equal(stake.Validator[:], txParam.Validator[:]) {
we should not add something, but we should check validator match and return BadValidator or ValidatorMismatch when it does not match. need to check somewhere. check these:
- stake owner mismatch (permission denied)
- validator key mismatch (validator mismatch)

2019-12-17 06:36 UTC, Lbird commented on amo/tx/tx.go
> +	ConfigLockupPeriod = defaultLockupPeriod
This will raise conflict when merging. merge from the recent master branch to avoid conflict.

2019-12-18 01:50 UTC, Lbird approved these changes

2019-12-18 01:50 UTC, merged