Enable unfungible assets' permission delegation
amolabs/amoabci pull request #189
Opened 2019-12-17 02:09 UTC by h0n9

- add 'ProxyAccount' property
- check 'ProxyAccount' permission
- add corresponding unit test codes

resolves https://github.com/amolabs/amoabci/issues/179

2019-12-17 04:45 UTC, h0n9 commented
update for docs in https://github.com/amolabs/docs/commit/9955f6ac72dec3e71b4ed2664d803f9b0042f470

2019-12-17 06:41 UTC, Lbird requested changes

2019-12-17 06:41 UTC, Lbird commented on amo/tx/discard.go
> +		return code.TxCodePermissionDenied, "parcel not permitted", nil
parcel not permitted --> permission denied

2019-12-17 06:41 UTC, Lbird commented on amo/tx/grant.go
> +		!bytes.Equal(parcel.ProxyAccount, t.GetSender()) {
Do this for TxRevoke also.

2019-12-18 02:04 UTC, Lbird approved these changes

2019-12-18 03:07 UTC, merged