Console commands for managing clients' private key
amolabs/amoabci pull request #26
Opened 2019-02-27 04:41 UTC by h0n9

Supported Commands:

* **list**: check the existing private keys stored on local area ($HOME/.amocli/key/)
* **generate**: generate a private key with nickname and store it (if want, after encrypting with a passphrase)
* **remove**: remove the private key specified by nickname (if encrypted, request passphrase to unlock it)

While generating a private key, a user can choose whether encrypting the key or not with option
(implementation for tests)

The keys are stored on local area as `keys.json` file which is placed in `$HOME/.amocli/key`

closes https://github.com/amolabs/amoabci/issues/20

2019-02-27 06:29 UTC, Lbird requested changes

2019-02-27 06:29 UTC, Lbird commented on cmd/amocli/keys/manage.go
> +		privKeyBytes = xsalsa20symmetric.EncryptSymmetric(privKey.Bytes(), crypto.Sha256(passphrase))
이 암호 알고리즘의 정체를 정확히 모르겠는데, 지금은 그냥 가지만 어쩌면 바꿔야 할 지도 모르겠네요.

2019-02-27 06:29 UTC, Lbird commented on cmd/amocli/keys/manage.go
> +	Address   []byte `json:"address"`
address의 type을 string으로 바꿔 주세요. amolabs/docs/protocol.md 문서에서 address 부분 참고하시기 바랍니다.

2019-02-27 06:29 UTC, Lbird commented on cmd/amocli/keys/manage.go
> +	PubKey    []byte `json:"pub_key"`
address 가지고도 private key 맞춰 볼 수 있으니 pub_key는 굳이 필요 없을 것 같은데요. 여기는 그냥 두더라도 key list 명령에서 화면에 기본으로 출력하지는 않아도 되지 않을까 합니다.

2019-02-27 06:34 UTC, Lbird commented
그리고 test 코드 추가해 주세요.

2019-02-27 07:02 UTC, h0n9 commented on cmd/amocli/keys/manage.go
> +		privKeyBytes = xsalsa20symmetric.EncryptSymmetric(privKey.Bytes(), crypto.Sha256(passphrase))
tendermit-amo/crypto 에서 자체적으로 지원하는 대칭 암호화 방식 같아서 가져다 써봤습니다.

2019-03-04 05:24 UTC, h0n9 commented
> 그리고 test 코드 추가해 주세요.

다른 commands 와 같이 issue 하나 생성해서 test code 추가하도록 하겠습니다.

2019-03-04 08:35 UTC, Lbird approved these changes

2019-03-04 08:36 UTC, merged