AMO abci operation
amolabs/amoabci pull request #34
Opened 2019-03-04 09:05 UTC by Crepepepe

resolve #2 #7

2019-03-04 10:46 UTC, Lbird requested changes
Execute 시점에도 operation이 valid한지 확인해야 합니다.

그리고, 여기도 역시 테스트 코드가 많이 부족한데 재홍씨처럼 별도로 작업해 넣을 예정인가요?

2019-03-04 10:46 UTC, Lbird commented on amo/amo.go
> +	app.store.SetBalance(b, 3000)
이건 테스트를 위해서인가요? comment 달아서 표시 좀 해 주세요.

2019-03-04 10:46 UTC, Lbird commented on amo/operation/tx.go
> +	return message, payload.(Operation)
error handling 하나 넣어야 하지 않을까요?

2019-03-04 10:52 UTC, Crepepepe commented on amo/operation/tx.go
> +	return message, payload.(Operation)
이미 switch 문에서 operation이 아니라면 panic이 발생하도록 했기때문에 다시 handling하는건 의미가 없다고 생각합니다.

2019-03-04 10:52 UTC, Crepepepe commented on amo/amo.go
> +	app.store.SetBalance(b, 3000)
테스트를 위해서 작성했습니다. 추후에 지울 예정입니다.

2019-03-04 10:53 UTC, Crepepepe commented
@Lbird test를 하려면 abci랑 tm을 실행시켜야 해서 tendermint 참고해서 작성해도록 하겠습니다.

2019-03-05 05:18 UTC, Lbird requested changes
--- FAIL: TestParseTx (0.00s)
    tx_test.go:30:
        	Error Trace:	tx_test.go:30
        	Error:      	Should be true
        	Test:       	TestParseTx
FAIL

2019-03-05 08:38 UTC, Lbird commented
> --- FAIL: TestParseTx (0.00s)
> tx_test.go:30:
> Error Trace:	tx_test.go:30
> Error: Should be true
> Test: TestParseTx
> FAIL

이게 실패하는 걸 보니 tendermint-amo에서 p256 관련 변경 사항 때문인 듯 하군요. 더 자세히 추적해 보진 않았는데, tendermint-amo f32f56fe77865f84e452409e7b0e68e39fc9f3e8 를 사용할 때는 문제가 없고 tendermint-amo a90bb406b7faa9b8fb3d3b78b16240e346ef53c7 (최신임)을 사용할 때는 문제가 있군요. 지금 master에는 Gopkg.lock이 업데이트 돼서 a90bb4를 사용하도록 돼 있으니 master에 이 PR이 merge 된 후에 고치는 게 낫겠습니다. 그래야 추적하기도 더 수월할 듯 하군요.

2019-03-05 08:38 UTC, Lbird approved these changes

2019-03-05 08:42 UTC, merged