Feature/8 add cli commands for parce related data
amolabs/amoabci pull request #56
Opened 2019-03-10 18:52 UTC by h0n9

- Modification on 'transfer' operation to make it fully functional
- Support of 6 of parcel-related operations
- Minor modification on coding structures for ease of development 

MakeMessage -> Sign Payload -> Signature, SigningPubKey, Signer(Address), Payload, etc..
(unfortunately verification on amoabci server's `checkTx()` is not supported yet)

```
type Message struct {
	Command       string          `json:"command"`
	Signer        crypto.Address  `json:"signer"`
	SigningPubKey p256.PubKeyP256 `json:"singingPubKey"`
	Signature     cmn.HexBytes    `json:"signature"`
	Payload       json.RawMessage `json:"payload"`
	Nonce         uint32          `json:"nonce"`
}
```

```
/* Commands (expected hierarchy)
 *
 * amocli |- tx |- transfer --to <address> --amount <uint64>
 *		|
 *		|- register --target <file> --custody <key>
 *		|- request --target <file> --payment <uint64>
 *		|- cancel --target <file>
 *		|
 *		|- grant --target <file> --grantee <address> --custody <key>
 *		|- revoke --target <file> --grantee <address>
 *		|- discard --target <file>
 */
```

resolves https://github.com/amolabs/amoabci/issues/8

2019-03-10 18:56 UTC, h0n9 commented
After parcel-related operations' descriptions on [rpc.md](https://github.com/amolabs/docs/blob/master/rpc.md) are full set, each of operation's description on CLI is planned to get improved for better understanding.

2019-03-11 01:41 UTC, Lbird requested changes

2019-03-11 01:41 UTC, Lbird commented on client/keys/util.go
> +func GetKeyToSign(path string) (Key, error) {
why don''t you change the name to 'SelectKey...'?

2019-03-11 01:41 UTC, Lbird commented on client/keys/util.go
> +	key = keyList[nickname]
recommend refactoring. not very clear distinction between getkey...() and check().

2019-03-11 01:41 UTC, Lbird commented on client/keys/util.go
> +	nickname = strings.Replace(nickname, "\r\n", "", -1)
is it necessary? what about using Trim()?

2019-03-11 01:41 UTC, Lbird commented on client/keys/util.go
> +		return key, errors.New("The key doesn't exist")
purpose of this function is to select one of the existing keys, then this error message is confusing. what? doesn't exist?

2019-03-11 01:41 UTC, Lbird commented on client/keys/util.go
> +func GetDecryptedKey(key *Key) error {
this function "transforms" the key that we already have. what about renaming it to "decrypt key".

2019-03-11 01:41 UTC, Lbird commented on client/rpc/broadcast.go
> +func Transfer(to crypto.Address, amount *atypes.Currency, sign bool) (*ctypes.ResultBroadcastTxCommit, error) {
after we start to support signed transaction, signing a transaction should be mandatory. an unsigned transaction will be not an option. and this comment applies to other transactions: register, request, ...

2019-03-11 01:41 UTC, Lbird commented on client/rpc/rpc.go
> +func MakeMessage(t string, nonce uint32, payload interface{}, sign bool) (types.Tx, error) {
refer to the comment to the Transfer() function.

2019-03-11 01:41 UTC, Lbird commented on client/rpc/rpc.go
> +func MakeMessage(t string, nonce uint32, payload interface{}, sign bool) (types.Tx, error) {
Think about this situation: we got a key to sign a transaction, but we don't care how. we just got a key. then, we just need a function to make a formed or formatted message. one unit of a code does one thing: make something from the prepared ingredients. think about layers or hierarchy of functions.

2019-03-11 13:02 UTC, Lbird approved these changes

2019-03-11 13:03 UTC, merged